# Generated by Django 3.0.14 on 2022-01-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='m', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchArm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchBack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchChest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchHeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchRise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchShoulder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchThigh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchWeight',
            field=models.IntegerField(default=0),
        ),
    ]
