# Generated by Django 3.0.14 on 2022-01-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220119_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outseamW', models.IntegerField(default=0)),
                ('outseamB', models.IntegerField(default=0)),
                ('waistW', models.IntegerField(default=0)),
                ('waistB', models.IntegerField(default=0)),
                ('thighW', models.IntegerField(default=0)),
                ('thighB', models.IntegerField(default=0)),
                ('riseW', models.IntegerField(default=0)),
                ('riseB', models.IntegerField(default=0)),
                ('backW', models.IntegerField(default=0)),
                ('backB', models.IntegerField(default=0)),
                ('shoulderW', models.IntegerField(default=0)),
                ('shoulderB', models.IntegerField(default=0)),
                ('armW', models.IntegerField(default=0)),
                ('armB', models.IntegerField(default=0)),
                ('chestW', models.IntegerField(default=0)),
                ('chestB', models.IntegerField(default=0)),
            ],
        ),
    ]
