# Generated by Django 3.0.14 on 2022-01-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_weightbias'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightbias',
            name='model_pk',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
