# Generated by Django 3.0.14 on 2022-01-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_weightbias_model_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightbias',
            name='armB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='armW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='backB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='backW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='chestB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='chestW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='outseamB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='outseamW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='riseB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='riseW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='shoulderB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='shoulderW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='thighB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='thighW',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='waistB',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightbias',
            name='waistW',
            field=models.FloatField(default=0),
        ),
    ]
