# node base 이미지 예전 버전을 사용하여 createRequest is not a function 이라는 에러가 발생했다. 최신 버전을 유지할 것
FROM node:14.18.2
WORKDIR /app
    # package.json을 ./ 폴더로 복사
COPY ./package.json ./

 RUN npm install --save --legacy-peer-deps



COPY ./ ./
CMD [ "npm" , "run" , "start" ]
