language: node_js

cache:
  directories:
    - node_modules
    
sudo: required

services:
  - docker

before_install:
  - docker build -t zolzak/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true zolzak/react-test-app npm run test

after_success:
  - docker build -t zolzak/docker-frontend ./frontend
  - docker build -t zolzak/docker-backend ./backend
  - docker build -t zolzak/docker-nginx ./nginx
  
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push zolzak/docker-frontend
  - docker push zolzak/docker-backend
  - docker push zolzak/docker-nginx

  